import fs from 'node:fs';
import path from 'node:path';

type BlogImageEntry = {
  image: string;
  alt: string;
};

type RawBlogPost = {
  slug?: string;
  title?: string;
  locale?: string;
  featuredImage?: {
    url?: string;
    alt?: string;
  };
};

function normalizeKey(input: string): string {
  const withoutHash = input.split('#')[0] ?? input;
  const withoutQuery = withoutHash.split('?')[0] ?? withoutHash;
  if (withoutQuery.length > 1 && withoutQuery.endsWith('/')) {
    return withoutQuery.slice(0, -1);
  }
  return withoutQuery;
}

function readJsonFile(filePath: string): RawBlogPost | null {
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    return JSON.parse(content) as RawBlogPost;
  } catch {
    return null;
  }
}

function main() {
  const contentRoot = path.join(process.cwd(), 'content', 'blog');
  const locales = ['en', 'fr', 'es', 'zh'] as const;

  const map: Record<string, BlogImageEntry> = {};
  const warnings: string[] = [];

  for (const locale of locales) {
    const localeDir = path.join(contentRoot, locale);
    if (!fs.existsSync(localeDir)) {
      warnings.push(`[generate-blog-featured-image-map] Missing locale dir: ${localeDir}`);
      continue;
    }

    const files = fs.readdirSync(localeDir).filter((f) => f.endsWith('.json'));
    for (const file of files) {
      const filePath = path.join(localeDir, file);
      const post = readJsonFile(filePath);
      if (!post?.slug) {
        warnings.push(`[generate-blog-featured-image-map] Skipping (no slug): ${filePath}`);
        continue;
      }
      const image = post.featuredImage?.url?.trim() || '';
      const alt = post.featuredImage?.alt?.trim() || post.title?.trim() || '';

      if (!image) {
        warnings.push(`[generate-blog-featured-image-map] Skipping (no featuredImage.url): ${filePath}`);
        continue;
      }
      if (!alt) {
        warnings.push(`[generate-blog-featured-image-map] Missing alt/title: ${filePath}`);
      }

      const localizedKey = normalizeKey(`/${locale}/blog/${post.slug}`);
      map[localizedKey] = { image, alt: alt || post.slug };

      // Canonical non-locale blog paths are treated as English.
      if (locale === 'en') {
        const canonicalKey = normalizeKey(`/blog/${post.slug}`);
        map[canonicalKey] = { image, alt: alt || post.slug };
      }
    }
  }

  const outPath = path.join(process.cwd(), 'src', 'generated', 'blog-featured-image-map.ts');
  const header =
    '// This file is auto-generated by scripts/blog/generate-blog-featured-image-map.ts\n' +
    '// Do not edit manually.\n\n' +
    "export type BlogFeaturedImageEntry = { image: string; alt: string };\n" +
    'export const BLOG_FEATURED_IMAGE_MAP: Record<string, BlogFeaturedImageEntry> = ';

  const body = `${JSON.stringify(map, null, 2)};\n`;

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, header + body, 'utf8');

  if (warnings.length > 0) {
    // eslint-disable-next-line no-console
    console.warn(warnings.join('\n'));
  }

  // eslint-disable-next-line no-console
  console.log(`[generate-blog-featured-image-map] Wrote ${Object.keys(map).length} entries to ${outPath}`);
}

main();
