#!/usr/bin/env tsx
/**
 * SEO Build Report Generator (T49)
 *
 * Generates an SEO health report during builds.
 * Run with: pnpm tsx scripts/seo/generate-seo-report.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { generateLinkSuggestions } from '../../src/lib/seo/link-suggestions';
import { TOPIC_CLUSTERS } from '../../src/lib/seo/topic-clusters';

interface SEOReport {
  generatedAt: string;
  summary: {
    pagesWithEnhancedSEO: number;
    totalEstimatedPages: number;
    coverage: string;
    schemaFeatures: {
      aggregateRating: boolean;
      breadcrumbs: boolean;
      faq: boolean;
      product: boolean;
    };
  };
  linkSuggestions: {
    total: number;
    byPriority: {
      high: number;
      medium: number;
      low: number;
    };
  };
  topicClusters: Array<{
    name: string;
    hubPage: string;
    spokesCount: number;
  }>;
  recommendations: string[];
}

// Pages known to use useEnhancedSEO
const PAGES_WITH_ENHANCED_SEO = [
  // Product pages
  '/products/trial-size',
  '/products/standard',
  '/products/family-pack',
  // Main pages
  '/',
  '/about',
  '/contact',
  '/privacy',
  '/terms',
  '/shipping',
  '/returns',
  '/stores',
  '/faq',
  // B2B pages
  '/veterinarians',
  '/hospitality',
  '/b2b/sell-sheet',
  '/invest',
  // Utility pages
  '/affiliate',
  '/affiliate/signup',
  '/ammonia-control',
  '/documents',
  '/support',
  '/try-free',
  '/tools/cat-litter-calculator',
  '/refer/[code]',
  '/blog',
  '/learn',
];

const TOTAL_ESTIMATED_PAGES = 50;

function generateReport(): SEOReport {
  const suggestions = generateLinkSuggestions();
  const highPriority = suggestions.filter((s) => s.priority === 'high').length;
  const mediumPriority = suggestions.filter((s) => s.priority === 'medium').length;
  const lowPriority = suggestions.filter((s) => s.priority === 'low').length;

  const coverage = Math.round(
    (PAGES_WITH_ENHANCED_SEO.length / TOTAL_ESTIMATED_PAGES) * 100
  );

  const recommendations: string[] = [];

  // Generate recommendations based on current state
  if (coverage < 80) {
    recommendations.push(`Increase Enhanced SEO coverage (currently ${coverage}%, target 80%+)`);
  }

  if (highPriority > 10) {
    recommendations.push(`Address ${highPriority} high-priority link suggestions for better internal linking`);
  }

  if (TOPIC_CLUSTERS.length < 5) {
    recommendations.push('Consider adding more topic clusters to improve content organization');
  }

  return {
    generatedAt: new Date().toISOString(),
    summary: {
      pagesWithEnhancedSEO: PAGES_WITH_ENHANCED_SEO.length,
      totalEstimatedPages: TOTAL_ESTIMATED_PAGES,
      coverage: `${coverage}%`,
      schemaFeatures: {
        aggregateRating: true, // Deployed in Phase 8
        breadcrumbs: true, // Deployed in Phase 8
        faq: true, // Already existed
        product: true, // Already existed
      },
    },
    linkSuggestions: {
      total: suggestions.length,
      byPriority: {
        high: highPriority,
        medium: mediumPriority,
        low: lowPriority,
      },
    },
    topicClusters: TOPIC_CLUSTERS.map((cluster) => ({
      name: cluster.name,
      hubPage: cluster.hubPage,
      spokesCount: cluster.spokes.length,
    })),
    recommendations,
  };
}

function formatReportAsMarkdown(report: SEOReport): string {
  const lines: string[] = [
    '# SEO Health Report',
    '',
    `**Generated:** ${new Date(report.generatedAt).toLocaleString()}`,
    '',
    '## Summary',
    '',
    '| Metric | Value |',
    '|--------|-------|',
    `| Enhanced SEO Coverage | ${report.summary.coverage} (${report.summary.pagesWithEnhancedSEO}/${report.summary.totalEstimatedPages} pages) |`,
    `| Link Suggestions | ${report.linkSuggestions.total} total |`,
    `| High Priority Links | ${report.linkSuggestions.byPriority.high} |`,
    `| Topic Clusters | ${report.topicClusters.length} |`,
    '',
    '## Schema Features',
    '',
    '| Feature | Status |',
    '|---------|--------|',
    `| Aggregate Rating | ${report.summary.schemaFeatures.aggregateRating ? '✅' : '❌'} |`,
    `| Breadcrumbs | ${report.summary.schemaFeatures.breadcrumbs ? '✅' : '❌'} |`,
    `| FAQ | ${report.summary.schemaFeatures.faq ? '✅' : '❌'} |`,
    `| Product | ${report.summary.schemaFeatures.product ? '✅' : '❌'} |`,
    '',
    '## Topic Clusters',
    '',
  ];

  report.topicClusters.forEach((cluster) => {
    lines.push(`- **${cluster.name}** - ${cluster.hubPage} (${cluster.spokesCount} spokes)`);
  });

  if (report.recommendations.length > 0) {
    lines.push('');
    lines.push('## Recommendations');
    lines.push('');
    report.recommendations.forEach((rec) => {
      lines.push(`- ${rec}`);
    });
  }

  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('*Generated by SEO Build Report Generator*');

  return lines.join('\n');
}

function main() {
  console.log('🔍 Generating SEO Report...\n');

  const report = generateReport();

  // Output to console
  console.log('📊 SEO Health Summary');
  console.log('=====================');
  console.log(`Coverage: ${report.summary.coverage}`);
  console.log(`Link Suggestions: ${report.linkSuggestions.total} (${report.linkSuggestions.byPriority.high} high priority)`);
  console.log(`Topic Clusters: ${report.topicClusters.length}`);
  console.log('');

  // Check for recommendations
  if (report.recommendations.length > 0) {
    console.log('⚠️  Recommendations:');
    report.recommendations.forEach((rec) => {
      console.log(`   - ${rec}`);
    });
    console.log('');
  } else {
    console.log('✅ No recommendations - SEO health is good!\n');
  }

  // Save JSON report
  const reportsDir = path.join(process.cwd(), '.seo-reports');
  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir, { recursive: true });
  }

  const jsonPath = path.join(reportsDir, 'latest.json');
  fs.writeFileSync(jsonPath, JSON.stringify(report, null, 2));
  console.log(`📄 JSON report saved to: ${jsonPath}`);

  // Save markdown report
  const mdPath = path.join(reportsDir, 'latest.md');
  fs.writeFileSync(mdPath, formatReportAsMarkdown(report));
  console.log(`📄 Markdown report saved to: ${mdPath}`);

  // Archive with timestamp
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const archivePath = path.join(reportsDir, `report-${timestamp}.json`);
  fs.writeFileSync(archivePath, JSON.stringify(report, null, 2));
  console.log(`📦 Archived to: ${archivePath}`);

  console.log('\n✅ SEO Report generated successfully!');

  // Return exit code based on health
  const hasWarnings = report.recommendations.length > 0;
  process.exit(hasWarnings ? 0 : 0); // Always exit 0, just log warnings
}

main();
