-- Enable RLS on every API-exposed public table.
-- No policies are added here on purpose: this locks down PostgREST access
-- while preserving server-side access through Prisma and the Supabase service role.

ALTER TABLE IF EXISTS "public"."billing_addresses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."retailers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."retailer_orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."retailer_order_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."VerificationToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."Product" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."OrderItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."Referral" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."referral_codes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."referral_redemptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."customers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."audit_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."leads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."social_posts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."carts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."customer_metrics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."blog_posts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."subscriptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."Account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."referral_rewards" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."blog_images" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."shipping_addresses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."subscription_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."affiliate_applications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."waitlists" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."Order" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."email_subscribers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."reviews" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."review_votes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."affiliate_conversions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."affiliate_payouts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."affiliate_clicks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."affiliates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."freshness_profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."_prisma_migrations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "public"."User" ENABLE ROW LEVEL SECURITY;
